require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/email_communications", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # EmailCommunication. As you add validations to EmailCommunication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # EmailCommunicationsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmailCommunication.create! valid_attributes
      get email_communications_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      email_communication = EmailCommunication.create! valid_attributes
      get email_communication_url(email_communication), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmailCommunication" do
        expect {
          post email_communications_url,
               params: { email_communication: valid_attributes }, headers: valid_headers, as: :json
        }.to change(EmailCommunication, :count).by(1)
      end

      it "renders a JSON response with the new email_communication" do
        post email_communications_url,
             params: { email_communication: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmailCommunication" do
        expect {
          post email_communications_url,
               params: { email_communication: invalid_attributes }, as: :json
        }.to change(EmailCommunication, :count).by(0)
      end

      it "renders a JSON response with errors for the new email_communication" do
        post email_communications_url,
             params: { email_communication: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested email_communication" do
        email_communication = EmailCommunication.create! valid_attributes
        patch email_communication_url(email_communication),
              params: { email_communication: new_attributes }, headers: valid_headers, as: :json
        email_communication.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the email_communication" do
        email_communication = EmailCommunication.create! valid_attributes
        patch email_communication_url(email_communication),
              params: { email_communication: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the email_communication" do
        email_communication = EmailCommunication.create! valid_attributes
        patch email_communication_url(email_communication),
              params: { email_communication: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested email_communication" do
      email_communication = EmailCommunication.create! valid_attributes
      expect {
        delete email_communication_url(email_communication), headers: valid_headers, as: :json
      }.to change(EmailCommunication, :count).by(-1)
    end
  end
end
