require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/journeys", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Journey. As you add validations to Journey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # JourneysController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Journey.create! valid_attributes
      get journeys_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      journey = Journey.create! valid_attributes
      get journey_url(journey), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Journey" do
        expect {
          post journeys_url,
               params: { journey: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Journey, :count).by(1)
      end

      it "renders a JSON response with the new journey" do
        post journeys_url,
             params: { journey: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Journey" do
        expect {
          post journeys_url,
               params: { journey: invalid_attributes }, as: :json
        }.to change(Journey, :count).by(0)
      end

      it "renders a JSON response with errors for the new journey" do
        post journeys_url,
             params: { journey: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested journey" do
        journey = Journey.create! valid_attributes
        patch journey_url(journey),
              params: { journey: new_attributes }, headers: valid_headers, as: :json
        journey.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the journey" do
        journey = Journey.create! valid_attributes
        patch journey_url(journey),
              params: { journey: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the journey" do
        journey = Journey.create! valid_attributes
        patch journey_url(journey),
              params: { journey: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested journey" do
      journey = Journey.create! valid_attributes
      expect {
        delete journey_url(journey), headers: valid_headers, as: :json
      }.to change(Journey, :count).by(-1)
    end
  end
end
